export const LOAD_VEHICLES_SUCCESS = 'LOAD_VEHICLES_SUCCESS';
export const LOAD_VEHICLES_FAILURE = 'LOAD_VEHICLES_FAILURE';
export const SELECT_VEHICLE = 'SELECT_VEHICLE';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_FILTER_TEXT = 'SET_FILTER_TEXT';
export const SET_SORT_OPTION = 'SET_SORT_OPTION';
